# Generated by Django 5.0.3 on 2024-05-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_archivedpost_archivepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivepost',
            old_name='archived_at',
            new_name='date_archived',
        ),
    ]
