# Generated by Django 5.0.3 on 2024-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_archived_at_archivepost_date_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is Archived'),
        ),
    ]
