# Generated by Django 5.0.3 on 2024-05-05 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_comment_date_comment_date_commented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked_by',
            new_name='likes',
        ),
    ]
