# Generated by Django 5.0.3 on 2024-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_comment_reply_comment_replies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivepost',
            options={'ordering': ['-date_archived']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_commented']},
        ),
        migrations.AlterModelOptions(
            name='savepost',
            options={'ordering': ['-date_saved']},
        ),
        migrations.AddField(
            model_name='comment',
            name='edited',
            field=models.BooleanField(default=False, verbose_name='Edited Comment'),
        ),
    ]
