# Generated by Django 5.0.3 on 2024-03-15 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20, verbose_name='Gender')),
                ('animal', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('PARROT', 'Parrot')], max_length=50, verbose_name='Animal')),
                ('breed', models.CharField(max_length=50, verbose_name='Breed')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Last log in')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
