# Generated by Django 5.0.3 on 2024-03-18 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date Last log in'),
        ),
    ]
