# Generated by Django 5.0.3 on 2024-03-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_managers_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='animal',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('PARROT', 'Parrot'), ('OTHER', 'Other')], max_length=50, verbose_name='Animal'),
        ),
    ]
