# Generated by Django 5.0.3 on 2024-03-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_securityquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='question',
            field=models.CharField(choices=[('favorite_toy', "What is your pet's favorite toy?"), ('favorite_treat', "What is your pet's favorite treat?"), ('best_friend', "What is the name of your pet's best friend?"), ('collar_color', "What is the color of your pet's collar?"), ('favorite_place_to_sleep', "What is your pet's favorite place to sleep?"), ('favorite_activity', "What is your pet's favorite activity?"), ('veterinarian_name', "What is the name of your pet's veterinarian?"), ('favorite_food', "What is your pet's favorite food?"), ('breed', 'What is the breed of your pet?'), ('birth_month', "What is your pet's birth month?"), ('favorite_game_to_play', "What is your pet's favorite game to play?"), ('nickname', "What is your pet's nickname?")], max_length=150, verbose_name='Question'),
        ),
    ]
