# Generated by Django 5.0.3 on 2024-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=None, max_length=100, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
