# Generated by Django 5.0.3 on 2024-03-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_userfollowing_accountfollowing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountfollowing',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='accountfollowing',
            old_name='following_id',
            new_name='following',
        ),
    ]
