# Generated by Django 5.0.3 on 2024-03-25 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_follower_id_accountfollowing_follower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='users.account')),
                ('users', models.ManyToManyField(related_name='blocked_by', to='users.account', verbose_name='Blocked Users')),
            ],
        ),
    ]
