# Generated by Django 5.0.3 on 2024-03-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_accountblocked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountblocked',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=None),
            preserve_default=False,
        ),
    ]
