# Generated by Django 5.0.3 on 2024-03-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_accountblocked_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountBlocked',
            new_name='BlockAccount',
        ),
        migrations.RenameModel(
            old_name='AccountFollowing',
            new_name='FollowAccount',
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow_requests', to='users.account', verbose_name='From User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow_requests', to='users.account', verbose_name='To User')),
            ],
        ),
        migrations.AddConstraint(
            model_name='followrequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_follow_request'),
        ),
    ]
