# Generated by Django 5.0.3 on 2024-03-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_accountblocked_blockaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrequest',
            old_name='from_user',
            new_name='request_from',
        ),
        migrations.RenameField(
            model_name='followrequest',
            old_name='to_user',
            new_name='request_to',
        ),
    ]
