# Generated by Django 5.0.3 on 2024-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_rename_from_user_followrequest_request_from_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='followrequest',
            name='unique_follow_request',
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AddConstraint(
            model_name='followrequest',
            constraint=models.UniqueConstraint(fields=('request_from', 'request_to'), name='unique_follow_request'),
        ),
    ]
