# Generated by Django 5.0.3 on 2024-03-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_followaccount_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='private_account',
            new_name='private',
        ),
    ]
