# Generated by Django 5.0.3 on 2024-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_rename_private_account_account_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequest',
            name='status',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('DECLINE', 'Decline'), ('CANCELLED', 'Cancelled')], default=None, verbose_name='Request status'),
            preserve_default=False,
        ),
    ]
