# Generated by Django 5.0.3 on 2024-03-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_followrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('ACCEPT', 'Accept'), ('DECLINE', 'Decline'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], null=True, verbose_name='Request status'),
        ),
    ]
