# Generated by Django 5.0.3 on 2024-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_followrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='PENDING', verbose_name='Request status'),
        ),
    ]
