# Generated by Django 5.0.3 on 2024-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_followrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified account'),
        ),
    ]
